name: sabzee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter: 
    sdk: flutter

  intl: ^0.17.0
  expandable_bottom_sheet: ^1.1.1+1
  flutter_inner_drawer:  
    git: 
      url: https://github.com/kenjishiromajp/flutter_inner_drawer 
      ref: kenjishiromajp-update-for-2.12-null-safety-casting

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

